language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - FLASK=0.10.1
  - FLASK=0.9
  - FLASK=0.8.1
install:
  - pip install flask==$FLASK coverage --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python setup.py test
notifications:
  email:
    - christoph.heer@googlemail.com
