language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - FLASK=0.11.1
  - FLASK=0.10.1
  - FLASK=0.9
  - FLASK=0.8.1
matrix:
  exclude:
    - python: "3.3"
      env: FLASK=0.9
    - python: "3.3"
      env: FLASK=0.8.1
    - python: "3.4"
      env: FLASK=0.9
    - python: "3.4"
      env: FLASK=0.8.1
    - python: "3.5"
      env: FLASK=0.9
    - python: "3.5"
      env: FLASK=0.8.1
install:
  - pip install flask==$FLASK coverage
  - pip install -e .
script:
  - python setup.py test
notifications:
  email:
    - christoph.heer@googlemail.com
    - jonathan.como@gmail.com
